### ISSUE TITLE
Warning when compiling with GCC 5.2.1

### ISSUE THREAD

**Issue by BrianBTB** [fuzyll/libctf#3]
libctf/ctf.c:258:13: warning: ignoring return value of ‘read’, declared with attribute warn_unused_result [-Wunused-result]

**Comment by fuzyll** [comment]
Looking at the code, I can understand why a compiler would emit a warning like that. Under _normal_ circumstances, it shouldn't be an issue at all. I find it unlikely that you'd be able to `open`, but not `read`, `/dev/urandom`. But, I fixed it in e116aa121d72ff6e2c51b33ebdd6d36ea1f47148 anyway.

I can't actually seem to reproduce it with `gcc` (v5.4) or `clang` (v3.8), despite ensuring `-Wall`, `-Wextra`, and others are turned on (even `-Wunused-result` directly). So, if you see other warnings like this, please continue to report them!
